In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
data=pd.read_csv('auto.csv')
data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,?,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,?,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,?,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,1,158,audi,gas,std,four,sedan,fwd,front,105.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,1,?,audi,gas,std,four,wagon,fwd,front,105.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,1,158,audi,gas,turbo,four,sedan,fwd,front,105.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,0,?,audi,gas,turbo,two,hatchback,4wd,front,99.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,2,192,bmw,gas,std,two,sedan,rwd,front,101.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,0,192,bmw,gas,std,four,sedan,rwd,front,101.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,0,188,bmw,gas,std,two,sedan,rwd,front,101.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,0,188,bmw,gas,std,four,sedan,rwd,front,101.2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,1,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,0,?,bmw,gas,std,four,sedan,rwd,front,103.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0,?,bmw,gas,std,two,sedan,rwd,front,103.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,0,?,bmw,gas,std,four,sedan,rwd,front,110.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,2,121,chevrolet,gas,std,two,hatchback,fwd,front,88.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,1,98,chevrolet,gas,std,two,hatchback,fwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,0,81,chevrolet,gas,std,four,sedan,fwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
20,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,1,118,dodge,gas,std,two,hatchback,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,1,118,dodge,gas,turbo,two,hatchback,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,1,148,dodge,gas,std,four,hatchback,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,1,148,dodge,gas,std,four,sedan,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,1,148,dodge,gas,turbo,?,sedan,fwd,front,93.7,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,-1,110,dodge,gas,std,four,wagon,fwd,front,103.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
28,3,145,dodge,gas,turbo,two,hatchback,fwd,front,95.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
29,2,137,honda,gas,std,two,hatchback,fwd,front,86.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
175,-1,65,toyota,gas,std,four,sedan,fwd,front,102.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
176,-1,65,toyota,gas,std,four,hatchback,fwd,front,102.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
177,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
178,3,197,toyota,gas,std,two,hatchback,rwd,front,102.9,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
179,-1,90,toyota,gas,std,four,sedan,rwd,front,104.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
180,-1,?,toyota,gas,std,four,wagon,rwd,front,104.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
181,2,122,volkswagen,diesel,std,two,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
182,2,122,volkswagen,gas,std,two,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
183,2,94,volkswagen,diesel,std,four,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
184,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
185,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
186,2,94,volkswagen,diesel,turbo,four,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
187,2,94,volkswagen,gas,std,four,sedan,fwd,front,97.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
188,3,?,volkswagen,gas,std,two,convertible,fwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
189,3,256,volkswagen,gas,std,two,hatchback,fwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
190,0,?,volkswagen,gas,std,four,sedan,fwd,front,100.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
191,0,?,volkswagen,diesel,turbo,four,sedan,fwd,front,100.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
192,0,?,volkswagen,gas,std,four,wagon,fwd,front,100.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
193,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
194,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
195,-2,103,volvo,gas,std,four,sedan,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
196,-1,74,volvo,gas,std,four,wagon,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
197,-2,103,volvo,gas,turbo,four,sedan,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
198,-1,74,volvo,gas,turbo,four,wagon,rwd,front,104.3,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
199,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
200,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
201,-1,95,volvo,gas,std,four,sedan,rwd,front,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
202,-1,95,volvo,diesel,turbo,four,sedan,rwd,front,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
203,-1,95,volvo,gas,turbo,four,sedan,rwd,front,109.1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
data.isnull().sum()

symboling              0
normalized-losses      0
make                   0
fuel-type              0
aspiration             0
num-of-doors           0
body-style             0
drive-wheels           0
engine-location        0
wheel-base             0
length                 0
width                  0
height                 0
curb-weight            0
engine-type            0
num-of-cylinders       0
engine-size            0
fuel-system            0
bore                   0
stroke                 0
compression-ratio      0
horsepower             0
peak-rpm               0
city-mpg               0
highway-mpg            0
price                  0
3                    204
?                    204
alfa-romero          204
gas                  204
std                  204
two                  204
convertible          204
rwd                  204
front                204
88.6                 204
168.8                204
64.1                 204
48.8                 204
2548                 204
dohc                 204
four                 204
130                  204
mpfi                 204
3.47                 204
2.68                 204
9.0                  204
111                  204
5000                 204
21                   204
27                   204
13495                204
dtype: int64

In [4]:
data.replace("?",np.nan,inplace=True)

In [5]:
data.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
missing_data=data.isnull()
missing_data

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
4,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
5,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
7,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
8,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
9,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
10,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
11,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
12,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
13,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
14,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
15,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
16,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
17,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
18,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
19,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
20,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
21,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
22,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
23,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
24,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
25,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
26,False,False,False,False,False,True,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
27,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
28,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
29,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
174,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
175,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
176,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
177,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
178,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
179,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
180,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
181,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
182,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
183,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
184,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
185,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
186,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
187,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
188,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
189,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
190,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
191,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
192,False,True,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
193,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
194,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
195,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
196,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
197,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
198,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
199,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
200,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
201,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
202,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
203,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [7]:
df=data.copy()

In [8]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [9]:
#variable=["a","b"]
#data=pd.read_csv('filename',na_values=variable)

In [10]:
for column in missing_data.columns.values.tolist():
    print(column)
    print(missing_data[column].value_counts())
    print("")

symboling
False    204
Name: symboling, dtype: int64

normalized-losses
False    164
True      40
Name: normalized-losses, dtype: int64

make
False    204
Name: make, dtype: int64

fuel-type
False    204
Name: fuel-type, dtype: int64

aspiration
False    204
Name: aspiration, dtype: int64

num-of-doors
False    202
True       2
Name: num-of-doors, dtype: int64

body-style
False    204
Name: body-style, dtype: int64

drive-wheels
False    204
Name: drive-wheels, dtype: int64

engine-location
False    204
Name: engine-location, dtype: int64

wheel-base
False    204
Name: wheel-base, dtype: int64

length
False    204
Name: length, dtype: int64

width
False    204
Name: width, dtype: int64

height
False    204
Name: height, dtype: int64

curb-weight
False    204
Name: curb-weight, dtype: int64

engine-type
False    204
Name: engine-type, dtype: int64

num-of-cylinders
False    204
Name: num-of-cylinders, dtype: int64

engine-size
False    204
Name: engine-size, dtype: int64

fuel-system
False    204
Name: fuel-system, dtype: int64

bore
False    200
True       4
Name: bore, dtype: int64

stroke
False    200
True       4
Name: stroke, dtype: int64

compression-ratio
False    204
Name: compression-ratio, dtype: int64

horsepower
False    202
True       2
Name: horsepower, dtype: int64

peak-rpm
False    202
True       2
Name: peak-rpm, dtype: int64

city-mpg
False    204
Name: city-mpg, dtype: int64

highway-mpg
False    204
Name: highway-mpg, dtype: int64

price
False    200
True       4
Name: price, dtype: int64

3
True    204
Name: 3, dtype: int64

?
True    204
Name: ?, dtype: int64

alfa-romero
True    204
Name: alfa-romero, dtype: int64

gas
True    204
Name: gas, dtype: int64

std
True    204
Name: std, dtype: int64

two
True    204
Name: two, dtype: int64

convertible
True    204
Name: convertible, dtype: int64

rwd
True    204
Name: rwd, dtype: int64

front
True    204
Name: front, dtype: int64

88.6
True    204
Name: 88.6, dtype: int64

168.8
True    204
Name: 168.8, dtype: int64

64.1
True    204
Name: 64.1, dtype: int64

48.8
True    204
Name: 48.8, dtype: int64

2548
True    204
Name: 2548, dtype: int64

dohc
True    204
Name: dohc, dtype: int64

four
True    204
Name: four, dtype: int64

130
True    204
Name: 130, dtype: int64

mpfi
True    204
Name: mpfi, dtype: int64

3.47
True    204
Name: 3.47, dtype: int64

2.68
True    204
Name: 2.68, dtype: int64

9.0
True    204
Name: 9.0, dtype: int64

111
True    204
Name: 111, dtype: int64

5000
True    204
Name: 5000, dtype: int64

21
True    204
Name: 21, dtype: int64

27
True    204
Name: 27, dtype: int64

13495
True    204
Name: 13495, dtype: int64

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 52 columns):
symboling            204 non-null int64
normalized-losses    164 non-null object
make                 204 non-null object
fuel-type            204 non-null object
aspiration           204 non-null object
num-of-doors         202 non-null object
body-style           204 non-null object
drive-wheels         204 non-null object
engine-location      204 non-null object
wheel-base           204 non-null float64
length               204 non-null float64
width                204 non-null float64
height               204 non-null float64
curb-weight          204 non-null int64
engine-type          204 non-null object
num-of-cylinders     204 non-null object
engine-size          204 non-null int64
fuel-system          204 non-null object
bore                 200 non-null object
stroke               200 non-null object
compression-ratio    204 non-null float64
horsepower           202 non-null object
peak-rpm             202 non-null object
city-mpg             204 non-null int64
highway-mpg          204 non-null int64
price                200 non-null object
3                    0 non-null float64
?                    0 non-null float64
alfa-romero          0 non-null float64
gas                  0 non-null float64
std                  0 non-null float64
two                  0 non-null float64
convertible          0 non-null float64
rwd                  0 non-null float64
front                0 non-null float64
88.6                 0 non-null float64
168.8                0 non-null float64
64.1                 0 non-null float64
48.8                 0 non-null float64
2548                 0 non-null float64
dohc                 0 non-null float64
four                 0 non-null float64
130                  0 non-null float64
mpfi                 0 non-null float64
3.47                 0 non-null float64
2.68                 0 non-null float64
9.0                  0 non-null float64
111                  0 non-null float64
5000                 0 non-null float64
21                   0 non-null float64
27                   0 non-null float64
13495                0 non-null float64
dtypes: float64(31), int64(5), object(16)
memory usage: 83.0+ KB

In [12]:
df['normalized-losses']=df['normalized-losses'].fillna("0").astype(int)
df['normalized-losses'].replace("0",np.nan)
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,0,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
df.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,0,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,0,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,0,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [14]:
nf=data.copy()
nf.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,NaN,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,NaN,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
avg=nf["normalized-losses"].astype("float").mean()
avg

122.0

In [16]:
nf['normalized-losses'].replace(np.nan,avg,inplace=True)

In [17]:
nf.head()

,symboling,normalized-losses,make,fuel-type,aspiration,num-of-doors,body-style,drive-wheels,engine-location,wheel-base,...,130,mpfi,3.47,2.68,9.0,111,5000,21,27,13495
0,3,122,alfa-romero,gas,std,two,convertible,rwd,front,88.6,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,122,alfa-romero,gas,std,two,hatchback,rwd,front,94.5,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,164,audi,gas,std,four,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2,164,audi,gas,std,four,sedan,4wd,front,99.4,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2,122,audi,gas,std,two,sedan,fwd,front,99.8,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [18]:
nf['stroke'].replace(np.nan,nf['stroke'].astype('float').mean(),inplace=True)

In [19]:
nf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 52 columns):
symboling            204 non-null int64
normalized-losses    204 non-null object
make                 204 non-null object
fuel-type            204 non-null object
aspiration           204 non-null object
num-of-doors         202 non-null object
body-style           204 non-null object
drive-wheels         204 non-null object
engine-location      204 non-null object
wheel-base           204 non-null float64
length               204 non-null float64
width                204 non-null float64
height               204 non-null float64
curb-weight          204 non-null int64
engine-type          204 non-null object
num-of-cylinders     204 non-null object
engine-size          204 non-null int64
fuel-system          204 non-null object
bore                 200 non-null object
stroke               204 non-null object
compression-ratio    204 non-null float64
horsepower           202 non-null object
peak-rpm             202 non-null object
city-mpg             204 non-null int64
highway-mpg          204 non-null int64
price                200 non-null object
3                    0 non-null float64
?                    0 non-null float64
alfa-romero          0 non-null float64
gas                  0 non-null float64
std                  0 non-null float64
two                  0 non-null float64
convertible          0 non-null float64
rwd                  0 non-null float64
front                0 non-null float64
88.6                 0 non-null float64
168.8                0 non-null float64
64.1                 0 non-null float64
48.8                 0 non-null float64
2548                 0 non-null float64
dohc                 0 non-null float64
four                 0 non-null float64
130                  0 non-null float64
mpfi                 0 non-null float64
3.47                 0 non-null float64
2.68                 0 non-null float64
9.0                  0 non-null float64
111                  0 non-null float64
5000                 0 non-null float64
21                   0 non-null float64
27                   0 non-null float64
13495                0 non-null float64
dtypes: float64(31), int64(5), object(16)
memory usage: 83.0+ KB

In [20]:
nf.isnull().sum()

symboling              0
normalized-losses      0
make                   0
fuel-type              0
aspiration             0
num-of-doors           2
body-style             0
drive-wheels           0
engine-location        0
wheel-base             0
length                 0
width                  0
height                 0
curb-weight            0
engine-type            0
num-of-cylinders       0
engine-size            0
fuel-system            0
bore                   4
stroke                 0
compression-ratio      0
horsepower             2
peak-rpm               2
city-mpg               0
highway-mpg            0
price                  4
3                    204
?                    204
alfa-romero          204
gas                  204
std                  204
two                  204
convertible          204
rwd                  204
front                204
88.6                 204
168.8                204
64.1                 204
48.8                 204
2548                 204
dohc                 204
four                 204
130                  204
mpfi                 204
3.47                 204
2.68                 204
9.0                  204
111                  204
5000                 204
21                   204
27                   204
13495                204
dtype: int64

In [21]:
two=(df['num-of-doors']=='two').sum()
two

88

In [22]:
four=(df['num-of-doors']=='four').sum()
four

114

In [23]:
nf['num-of-doors'].replace(np.nan,four,inplace=True)

In [24]:
nf.isnull().sum()

symboling              0
normalized-losses      0
make                   0
fuel-type              0
aspiration             0
num-of-doors           0
body-style             0
drive-wheels           0
engine-location        0
wheel-base             0
length                 0
width                  0
height                 0
curb-weight            0
engine-type            0
num-of-cylinders       0
engine-size            0
fuel-system            0
bore                   4
stroke                 0
compression-ratio      0
horsepower             2
peak-rpm               2
city-mpg               0
highway-mpg            0
price                  4
3                    204
?                    204
alfa-romero          204
gas                  204
std                  204
two                  204
convertible          204
rwd                  204
front                204
88.6                 204
168.8                204
64.1                 204
48.8                 204
2548                 204
dohc                 204
four                 204
130                  204
mpfi                 204
3.47                 204
2.68                 204
9.0                  204
111                  204
5000                 204
21                   204
27                   204
13495                204
dtype: int64

In [25]:
f=(nf['num-of-doors']=='two').sum()
f

88

In [26]:
df['num-of-doors'].value_counts().idxmax()

'four'

In [27]:
df['highway-mpg-li']=(235/df['city-mpg'])

In [28]:
df['highway-mpg-li'].head()

0    11.190476
1    12.368421
2     9.791667
3    13.055556
4    12.368421
Name: highway-mpg-li, dtype: float64

In [29]:
df['highway-mpg'].head()

0    27
1    26
2    30
3    22
4    25
Name: highway-mpg, dtype: int64

In [30]:
df['horsepower'].astype('float').min()

48.0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 204 entries, 0 to 203
Data columns (total 53 columns):
symboling            204 non-null int64
normalized-losses    204 non-null int32
make                 204 non-null object
fuel-type            204 non-null object
aspiration           204 non-null object
num-of-doors         202 non-null object
body-style           204 non-null object
drive-wheels         204 non-null object
engine-location      204 non-null object
wheel-base           204 non-null float64
length               204 non-null float64
width                204 non-null float64
height               204 non-null float64
curb-weight          204 non-null int64
engine-type          204 non-null object
num-of-cylinders     204 non-null object
engine-size          204 non-null int64
fuel-system          204 non-null object
bore                 200 non-null object
stroke               200 non-null object
compression-ratio    204 non-null float64
horsepower           202 non-null object
peak-rpm             202 non-null object
city-mpg             204 non-null int64
highway-mpg          204 non-null int64
price                200 non-null object
3                    0 non-null float64
?                    0 non-null float64
alfa-romero          0 non-null float64
gas                  0 non-null float64
std                  0 non-null float64
two                  0 non-null float64
convertible          0 non-null float64
rwd                  0 non-null float64
front                0 non-null float64
88.6                 0 non-null float64
168.8                0 non-null float64
64.1                 0 non-null float64
48.8                 0 non-null float64
2548                 0 non-null float64
dohc                 0 non-null float64
four                 0 non-null float64
130                  0 non-null float64
mpfi                 0 non-null float64
3.47                 0 non-null float64
2.68                 0 non-null float64
9.0                  0 non-null float64
111                  0 non-null float64
5000                 0 non-null float64
21                   0 non-null float64
27                   0 non-null float64
13495                0 non-null float64
highway-mpg-li       204 non-null float64
dtypes: float64(32), int32(1), int64(5), object(15)
memory usage: 83.8+ KB

In [35]:
df['horsepower']=df['horsepower'].astype(float)

In [36]:
df['horsepower'].head()

0    111.0
1    154.0
2    102.0
3    115.0
4    110.0
Name: horsepower, dtype: float64

In [52]:
%matplotlib inline
import matplotlib.pyplot as plt

In [53]:
bins=np.linspace(min(df['horsepower']),(max(df['horsepower'])+1),4)
bins

array([ 48.        , 128.33333333, 208.66666667, 289.        ])

In [54]:
df['horsepower-binned']=pd.cut(df['horsepower'],bins,labels=['Low','Medium','High'],include_lowest=True)
df[['horsepower-binned','horsepower']].tail(20)

    horsepower-binned  horsepower
184               Low        85.0
185               Low        85.0
186               Low        68.0
187               Low       100.0
188               Low        90.0
189               Low        90.0
190               Low       110.0
191               Low        68.0
192               Low        88.0
193               Low       114.0
194               Low       114.0
195               Low       114.0
196               Low       114.0
197            Medium       162.0
198            Medium       162.0
199               Low       114.0
200            Medium       160.0
201            Medium       134.0
202               Low       106.0
203               Low       114.0

In [66]:
pd.set_option('display.max_rows',None)

In [67]:
df['horsepower']

0      111.0
1      154.0
2      102.0
3      115.0
4      110.0
5      110.0
6      110.0
7      140.0
8      160.0
9      101.0
10     101.0
11     121.0
12     121.0
13     121.0
14     182.0
15     182.0
16     182.0
17      48.0
18      70.0
19      70.0
20      68.0
21      68.0
22     102.0
23      68.0
24      68.0
25      68.0
26     102.0
27      88.0
28     145.0
29      58.0
30      76.0
31      60.0
32      76.0
33      76.0
34      76.0
35      76.0
36      86.0
37      86.0
38      86.0
39      86.0
40     101.0
41     100.0
42      78.0
43      70.0
44      70.0
45      90.0
46     176.0
47     176.0
48     262.0
49      68.0
50      68.0
51      68.0
52      68.0
53      68.0
54     101.0
55     101.0
56     101.0
57     135.0
58      84.0
59      84.0
60      84.0
61      84.0
62      64.0
63      84.0
64     120.0
65      72.0
66     123.0
67     123.0
68     123.0
69     123.0
70     155.0
71     155.0
72     184.0
73     184.0
74     175.0
75      68.0
76      68.0
77      68.0
78     102.0
79     116.0
80      88.0
81     145.0
82     145.0
83     145.0
84      88.0
85      88.0
86     116.0
87     116.0
88      69.0
89      55.0
90      69.0
91      69.0
92      69.0
93      69.0
94      69.0
95      69.0
96      69.0
97      69.0
98      97.0
99      97.0
100    152.0
101    152.0
102    152.0
103    160.0
104    200.0
105    160.0
106     97.0
107     95.0
108     97.0
109     95.0
110     95.0
111     95.0
112     95.0
113     95.0
114     97.0
115     95.0
116    142.0
117     68.0
118    102.0
119     68.0
120     68.0
121     68.0
122     88.0
123    145.0
124    143.0
125    207.0
126    207.0
127    207.0
128    288.0
129      NaN
130      NaN
131    110.0
132    110.0
133    110.0
134    110.0
135    160.0
136    160.0
137     69.0
138     73.0
139     73.0
140     82.0
141     82.0
142     94.0
143     82.0
144    111.0
145     82.0
146     94.0
147     82.0
148    111.0
149     62.0
150     62.0
151     62.0
152     62.0
153     62.0
154     62.0
155     70.0
156     70.0
157     56.0
158     56.0
159     70.0
160     70.0
161     70.0
162     70.0
163     70.0
164    112.0
165    112.0
166    116.0
167    116.0
168    116.0
169    116.0
170    116.0
171    116.0
172     92.0
173     73.0
174     92.0
175     92.0
176     92.0
177    161.0
178    161.0
179    156.0
180    156.0
181     52.0
182     85.0
183     52.0
184     85.0
185     85.0
186     68.0
187    100.0
188     90.0
189     90.0
190    110.0
191     68.0
192     88.0
193    114.0
194    114.0
195    114.0
196    114.0
197    162.0
198    162.0
199    114.0
200    160.0
201    134.0
202    106.0
203    114.0
Name: horsepower, dtype: float64